apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: wagtail-db
  description: Wagtail Postgres database
spec:
  type: database
  owner: group:default/nationalarchives
  system: tna-website